"""Constants for Ambilight Sync."""

DOMAIN = "ambilight_sync"
VERSION = "0.3.0"

CONF_SYSTEM = "system"

SERVICE_ACTIVATE_PRESET = "activate_preset"

CONF_ZONE_LEFT = "zone_left"
CONF_ZONE_RIGHT = "zone_right"
CONF_ZONE_TOP = "zone_top"
CONF_ZONE_BOTTOM = "zone_bottom"
CONF_ZONE_ALL = "zone_all"

CONF_ZONE_LEFT_CORNERS = "zone_left_corners"
CONF_ZONE_RIGHT_CORNERS = "zone_right_corners"
CONF_ZONE_TOP_CORNERS = "zone_top_corners"
CONF_ZONE_BOTTOM_CORNERS = "zone_bottom_corners"

CONF_SOURCE = "source"
CONF_COLOR_MODE = "color_mode"
CONF_POLL_RATE = "poll_rate"
CONF_UPDATE_RATE = "update_rate"
CONF_SMOOTHING = "smoothing"
CONF_BRIGHTNESS = "brightness"
CONF_MINIMUM_BRIGHTNESS = "minimum_brightness"
CONF_SATURATION = "saturation"
CONF_THRESHOLD = "threshold"
CONF_BLACK_THRESHOLD = "black_threshold"
CONF_TRANSITION = "transition"
CONF_BLACK_HOLD = "black_hold_ms"
CONF_FADE_TO_BLACK = "fade_to_black"
CONF_OFF_DELAY = "off_delay"
CONF_SCENE_CUT_THRESHOLD = "scene_cut_threshold"
CONF_SCENE_CUT_TRANSITION = "scene_cut_transition"
CONF_CORNER_INFLUENCE = "corner_influence"
CONF_RESTORE_ON_STOP = "restore_on_stop"

CONF_POSITION_MODE = "position_mode"
CONF_POSITION_X = "position_x"
CONF_POSITION_Y = "position_y"
CONF_POSITION_FALLOFF = "position_falloff"

POSITION_MODE_MANUAL = "manual"
POSITION_MODE_SPATIAL = "spatial"
POSITION_MODES = [POSITION_MODE_SPATIAL, POSITION_MODE_MANUAL]

SOURCE_PROCESSED = "processed"
SOURCE_MEASURED = "measured"
SOURCES = [SOURCE_PROCESSED, SOURCE_MEASURED]

COLOR_MODE_AVERAGE = "average"
COLOR_MODE_PERCEPTUAL = "perceptual"
COLOR_MODE_DOMINANT = "dominant"
COLOR_MODES = [COLOR_MODE_AVERAGE, COLOR_MODE_PERCEPTUAL, COLOR_MODE_DOMINANT]

ZONE_LEFT = "left"
ZONE_RIGHT = "right"
ZONE_TOP = "top"
ZONE_BOTTOM = "bottom"
ZONE_ALL = "all"
ZONE_LEFT_CORNERS = "left_corners"
ZONE_RIGHT_CORNERS = "right_corners"
ZONE_TOP_CORNERS = "top_corners"
ZONE_BOTTOM_CORNERS = "bottom_corners"

ZONES = [
    ZONE_LEFT,
    ZONE_RIGHT,
    ZONE_TOP,
    ZONE_BOTTOM,
    ZONE_ALL,
    ZONE_LEFT_CORNERS,
    ZONE_RIGHT_CORNERS,
    ZONE_TOP_CORNERS,
    ZONE_BOTTOM_CORNERS,
]

ZONE_CONFIG_KEYS = {
    ZONE_LEFT: CONF_ZONE_LEFT,
    ZONE_RIGHT: CONF_ZONE_RIGHT,
    ZONE_TOP: CONF_ZONE_TOP,
    ZONE_BOTTOM: CONF_ZONE_BOTTOM,
    ZONE_ALL: CONF_ZONE_ALL,
    ZONE_LEFT_CORNERS: CONF_ZONE_LEFT_CORNERS,
    ZONE_RIGHT_CORNERS: CONF_ZONE_RIGHT_CORNERS,
    ZONE_TOP_CORNERS: CONF_ZONE_TOP_CORNERS,
    ZONE_BOTTOM_CORNERS: CONF_ZONE_BOTTOM_CORNERS,
}

DEFAULT_SOURCE = SOURCE_PROCESSED
DEFAULT_COLOR_MODE = COLOR_MODE_AVERAGE
DEFAULT_UPDATE_RATE = 15.0
DEFAULT_POLL_RATE = DEFAULT_UPDATE_RATE
DEFAULT_SMOOTHING = 0.0
DEFAULT_BRIGHTNESS = 100.0
DEFAULT_MINIMUM_BRIGHTNESS = 0.0
DEFAULT_SATURATION = 100.0
DEFAULT_THRESHOLD = 6.0
DEFAULT_BLACK_THRESHOLD = 1.0
DEFAULT_TRANSITION = 0.1
DEFAULT_BLACK_HOLD = 0.0
DEFAULT_FADE_TO_BLACK = 0.0
DEFAULT_OFF_DELAY = 0.0
DEFAULT_SCENE_CUT_THRESHOLD = 35.0
DEFAULT_SCENE_CUT_TRANSITION = 0.05
DEFAULT_CORNER_INFLUENCE = 35.0
DEFAULT_RESTORE_ON_STOP = True
DEFAULT_POSITION_MODE = POSITION_MODE_MANUAL
DEFAULT_POSITION_X = 0.0
DEFAULT_POSITION_Y = 0.0
DEFAULT_POSITION_FALLOFF = 45.0

MIN_UPDATE_RATE = 0.25
MAX_UPDATE_RATE = 30.0
MIN_BLACK_THRESHOLD = 0.0
MAX_BLACK_THRESHOLD = 20.0
MIN_POSITION_FALLOFF = 5.0
MAX_POSITION_FALLOFF = 100.0
BLACK_HYSTERESIS_PERCENT = 2.0
STUCK_PROCESSED_SECONDS = 10.0
RATE_WINDOW_SECONDS = 10.0
CORNER_SLICE_FRACTION = 0.25

PANEL_URL = "ambilight-sync"
PANEL_COMPONENT = "ambilight-sync-panel"
PANEL_STATIC_URL = "/ambilight_sync_static"
